// Quotes resource

const quotes = [
    { id : 1, quote :'"PERFECT IS THE ENEMY OF GOOD." –VOLTAIRE'},
    { id : 2, quote :'"I’M STILL LEARNING." –MICHELANGELO'},
    { id : 3, quote :'"LIFE IS A JOURNEY, NOT A DESTINATION." –RALPH WALDO EMERSON'},
    { id : 4, quote :'"LEARNING IS NOT ATTAINED BY CHANCE, IT MUST BE SOUGHT FOR WITH ARDOR AND ATTENDED TO WITH DILIGENCE." ―ABIGAIL ADAMS'},
    { id : 5, quote :'"YESTERDAY I WAS CLEVER, SO I CHANGED THE WORLD. TODAY I AM WISE, SO I AM CHANGING MYSELF." –RUMI'},
    { id : 6, quote :'"BE CURIOUS, NOT JUDGMENTAL." –WALT WHITMAN'},
    { id : 7, quote :'"YOU DON’T HAVE TO BE GREAT TO START, BUT YOU HAVE TO START TO BE GREAT." –ZIG ZIGLAR'},
    { id : 8, quote :'"BE STUBBORN ABOUT YOUR GOALS AND FLEXIBLE ABOUT YOUR METHODS." –UNKNOWN'},
    { id : 9, quote :'"NOTHING WILL WORK UNLESS YOU DO." –MAYA ANGELOU'},
    { id : 10, quote :'"NEVER GIVE UP ON A DREAM JUST BECAUSE OF THE TIME IT WILL TAKE TO ACCOMPLISH IT. THE TIME WILL PASS ANYWAY." –EARL NIGHTINGALE'},
    { id : 11, quote :'"ANYONE WHO STOPS LEARNING IS OLD, WHETHER AT TWENTY OR EIGHTY." —HENRY FORD'},
    { id : 12, quote :'"TELL ME AND I FORGET. TEACH ME AND I REMEMBER. INVOLVE ME AND I LEARN." –BENJAMIN FRANKLIN'},
    { id : 13, quote :'"CHANGE IS THE END RESULT OF ALL TRUE LEARNING." ―LEO BUSCAGLIA'},
    { id : 14, quote :'"LIVE AS IF YOU WERE TO DIE TOMORROW. LEARN AS IF YOU WERE TO LIVE FOREVER." ―MAHATMA GANDHI'},
    { id : 15, quote :'"A LEARNING CURVE IS ESSENTIAL TO GROWTH." –TAMMY BJELLAND'},
  ]


module.exports = quotes;
